#!/usr/bin/env python3
"""Build the June 2013 Games/Fairytale catalog from saved archive pages.

The live archive only gives us the initially rendered WebForms category.  This
script deliberately preserves that bounded evidence rather than inventing the
server-side results of the other category tabs.
"""
from __future__ import annotations

import html
import json
import re
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ARCHIVE = "https://web.archive.org/web/20130628161553id_/http://www.barbie.com"
PAGES = {"fun_games": ROOT / "research/sections/games.html", "fantasy": ROOT / "research/sections/fantasy.html"}
PUBLIC = ROOT / "public"


def one(pattern: str, text: str, default: str = "") -> str:
    hit = re.search(pattern, text, re.S | re.I)
    return html.unescape(hit.group(1).strip()) if hit else default


def parse_page(kind: str, path: Path) -> tuple[dict, list[str]]:
    text = path.read_text(encoding="utf-8", errors="replace")
    tabs = []
    resources = []
    for match in re.finditer(r'<input[^>]+(?:id="gameslist_rptCategoryListing[^>]+|class="categoryButtonSel"[^>]+)[^>]*>', text, re.I):
        tag = match.group(0)
        src = one(r'\bsrc="([^"]+)', tag)
        alt = one(r'\balt="([^"]+)', tag)
        if src and alt:
            tabs.append({"id": alt, "image": src})
            resources.append(src)
    selected = one(r'id="gameslist_imgSelectedCategory"[^>]+src="([^"]+)', text)
    if selected:
        resources.append(selected)
    cards = []
    card_re = re.compile(r'<div id="gameslist_rptItemListing.*?class="itemthumb".*?onmouseover=".*?&quot;(.*?)&quot;.*?<a href="([^"]+)".*?<img src="([^"]+)".*?<span[^>]*>(.*?)</span>', re.S | re.I)
    for blurb, href, image, title in card_re.findall(text):
        cards.append({"title": html.unescape(re.sub(r"<.*?>", "", title)).strip(), "blurb": html.unescape(blurb), "href": html.unescape(href), "image": html.unescape(image)})
        resources.append(html.unescape(image))
    # These original chrome images appear in BarbieRefresh.css.
    resources.extend([
        "/images/barbie_refresh/agg_thumbBG.png", "/images/barbie_refresh/agg_thumbBG_hover.png",
        "/images/barbie_refresh/agg_center.png", "/images/barbie_refresh/agg_top.png",
        "/images/barbie_refresh/agg_bottom.jpg", "/images/games/global-tab-foreground-bar-all-selected.png",
    ])
    hero = "/activities/fun_games/gamesModule.swf" if kind == "fun_games" else "/activities/fantasy/fairyTale.swf"
    resources.append(hero)
    return {"tabs": tabs, "selected": selected, "cards": cards, "hero": hero}, sorted(set(resources))


def download(path: str) -> dict:
    local = PUBLIC / path.lstrip("/")
    local.parent.mkdir(parents=True, exist_ok=True)
    if local.exists() and local.stat().st_size and not local.read_bytes()[:128].lstrip().lower().startswith((b"<!doctype html", b"<html")):
        return {"original": path, "local": "/" + str(local.relative_to(PUBLIC)), "bytes": local.stat().st_size}
    if path == "/activities/fantasy/fairyTale.swf":
        shutil.copyfile(ROOT / "research/sections/fairyTale.swf", local)
    else:
        # curl is used instead of urllib: this workstation's archive proxy is
        # configured for curl and rejects Python's direct socket connection.
        temp = local.with_suffix(local.suffix + ".part")
        result = subprocess.run(["curl", "-L", "--fail", "--silent", "--show-error", "--retry", "1", "--retry-all-errors", "--retry-delay", "1", ARCHIVE + path, "-o", str(temp)])
        if result.returncode:
            temp.unlink(missing_ok=True)
            return {"original": path, "local": "/" + str(local.relative_to(PUBLIC)), "missing": True, "error": f"curl exit {result.returncode}"}
        payload = temp.read_bytes()
        # Wayback sometimes returns an HTML error response with a 200 status.
        if payload.lstrip().lower().startswith((b"<!doctype html", b"<html")):
            temp.unlink(missing_ok=True)
            return {"original": path, "local": "/" + str(local.relative_to(PUBLIC)), "missing": True, "error": "archive returned HTML"}
        temp.replace(local)
    return {"original": path, "local": "/" + str(local.relative_to(PUBLIC)), "bytes": local.stat().st_size}


def main() -> None:
    data, resources = {}, []
    for kind, page in PAGES.items():
        parsed, found = parse_page(kind, page)
        data[kind] = parsed
        resources.extend(found)
    target = PUBLIC / "sections/catalog-data.js"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("// Generated by scripts/build_catalog.py from June 2013 archive pages.\nexport const catalogData = " + json.dumps(data, ensure_ascii=False, indent=2) + ";\n", encoding="utf-8")
    assets = []
    for source in sorted(set(resources)):
        assets.append(download(source))
    (ROOT / "research/sections/catalog-assets.json").write_text(json.dumps({"archive": ARCHIVE, "assets": assets}, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {target.relative_to(ROOT)} and recovered {len(assets)} assets")


if __name__ == "__main__":
    try:
        main()
    except Exception as exc:
        print(f"catalog build failed: {exc}", file=sys.stderr)
        raise
